# Generated by Django 4.0.1 on 2022-02-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHistoryUser',
            fields=[
                ('user_id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_id', models.UUIDField(editable=False)),
                ('location_latitude', models.CharField(max_length=20)),
                ('location_longitude', models.CharField(max_length=20)),
                ('location_accuracy', models.CharField(max_length=20)),
                ('date', models.DateTimeField(verbose_name='date logged')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocationHistory.locationhistoryuser')),
            ],
        ),
    ]
