# Generated by Django 4.0.1 on 2022-02-22 05:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LocationHistory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationhistory',
            old_name='date',
            new_name='location_datetime',
        ),
        migrations.AlterField(
            model_name='locationhistory',
            name='log_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
