# Generated by Django 4.0.1 on 2022-02-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocationHistory', '0002_rename_date_locationhistory_location_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationhistory',
            old_name='reporter',
            new_name='user',
        ),
    ]
