# Generated by Django 4.0.1 on 2022-02-23 01:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LocationHistory', '0003_rename_reporter_locationhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LocationHistoryLogs', to='LocationHistory.locationhistoryuser'),
        ),
        migrations.AlterField(
            model_name='locationhistoryuser',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
    ]
